### PR TITLE
Upgrade dependencies

### PR DESCRIPTION
**Pull request by TheLudd**
Upgrades all non dev dependencies to the lasest (major) version. All
tests pass.

This PR is part of an effort to reduce non de-duplicatable modules in my projects.

### CODE REVIEW

**Comment by sindresorhus** [comment]
Have you checked each release note to ensure there are no changes that affects this package? Not everything is caught by tests. Also, I think some of those upgrades require Node.js 10.

**Comment by TheLudd** [comment]
Only breaking is node versions which is 10 for `type-fest` which I guess would be breaking for this package since it states `>=8` in `package.json`

**Comment by sindresorhus** [comment]
Correct

**Comment by TheLudd** [comment]
Maybe for next major then :)

**Pull request closed without merging**
